export const surpriseMePrompts = [
  'an armchair in the shape of an avocado',
  'a surrealist dream-like oil painting by Salvador Dalí of a cat playing checkers',
  'teddy bears shopping for groceries in Japan, ukiyo-e',
  'an oil painting by Matisse of a humanoid robot playing chess',
  'panda mad scientist mixing sparkling chemicals, digital art',
  "a macro 35mm photograph of two mice in Hawaii, they're each wearing tiny swimsuits and are carrying tiny surf boards, digital art",
  '3D render of a cute tropical fish in an aquarium on a dark blue background, digital art',
  'an astronaut lounging in a tropical resort in space, vaporwave',
  'an oil painting portrait of a capybara wearing medieval royal robes and an ornate crown on a dark background',
  'a stained glass window depicting a hamburger and french fries',
  'a pencil and watercolor drawing of a bright city in the future with flying cars',
  'a sunlit indoor lounge area with a pool with clear water and another pool with translucent pastel pink water, next to a big window, digital art',
  'a fortune-telling shiba inu reading your fate in a giant hamburger, digital art',
  '"a sea otter with a pearl earring" by Johannes Vermeer',
  'an oil pastel drawing of an annoyed cat in a spaceship',
  'a painting of a fox in the style of Starry Night',
  'a bowl of soup that looks like a monster, knitted out of wool',
  'A plush toy robot sitting against a yellow wall',
  'A synthwave style sunset above the reflecting water of the sea, digital art',
  'Two futuristic towers with a skybridge covered in lush foliage, digital art',
  'A 3D render of a rainbow colored hot air balloon flying above a reflective lake',
  'A comic book cover of a superhero wearing headphones',
  'A centered explosion of colorful powder on a black background',
  'A photo of a Samoyed dog with its tongue out hugging a white Siamese cat',
  'A photo of a white fur monster standing in a purple room',
  "A photo of Michelangelo's sculpture of David wearing headphones djing",
  'A Samurai riding a Horse on Mars, lomography.',
  'A modern, sleek Cadillac drives along the Gardiner expressway with downtown Toronto in the background, with a lens flare, 50mm photography',
  'A realistic photograph of a young woman with blue eyes and blonde hair',
  'A man standing in front of a stargate to another dimension',
  'Spongebob Squarepants in the Blair Witch Project',
  'A velociraptor working at a hotdog stand, lomography',
  'A man walking through the bustling streets of Kowloon at night, lit by many bright neon shop signs, 50mm lens',
  'A BBQ that is alive, in the style of a Pixar animated movie',
  'A futuristic cyborg dance club, neon lights',
  'The long-lost Star Wars 1990 Japanese Anime',
  'A hamburger in the shape of a Rubik’s cube, professional food photography',
  'A Synthwave Hedgehog, Blade Runner Cyberpunk',
  'An astronaut encountering an alien life form on a distant planet, photography',
  'A Dinosaur exploring Cape Town, photography',
  'A Man falling in Love with his Computer, digital art',
  'A photograph of a cyborg exploring Tokyo at night, lomography',
  'Dracula walking down the street of New York City in the 1920s, black and white photography',
  'Synthwave aeroplane',
  'A man wanders through the rainy streets of Tokyo, with bright neon signs, 50mm',
  'A Space Shuttle flying above Cape Town, digital art',
  'A skyscraper in the shape of a giant stapler',
  'A car that runs on recycled coffee grounds',
  'A phone charger in the shape of a cactus',
  'A bicycle with a built-in mini garden',
  'A lamp in the shape of a giant firefly',
  'A watch that tells time with flowers instead of numbers',
  'A refrigerator that doubles as a vertical herb garden',
  'A toaster that makes toast in the shape of your favorite animal',
  'A showerhead that plays music while you bathe',
  'A mirror that shows you different hairstyles before you commit to a cut',
  'A clock that tells time with different spices',
  'A fridge that gives you recipes based on what ingredients you have on hand',
  'A lamp that changes color based on your mood',
  'A phone case that also works as a mini green house',
  'A building that generates its own energy from the sun and wind',
  'A chair that can transform into a bed for unexpected guests',
  'A coffee table that also functions as an indoor fish pond',
  'A pen that can also be used as a stylus for your tablet',
  'A bookcase that doubles as a room divider',
  'A kitchen island that has a built-in BBQ grill',
  'A computer mouse in the shape of a miniature race car',
  'A lamp that can change brightness based on the time of day',
  'A toaster that can make waffles in the shape of your favorite cartoon character',
  'A pencil sharpener that also works as a phone charger',
  'A showerhead that has built-in aromatherapy features',
  'A mirror that can analyze your skin and recommend skincare products',
  'A clock that can also function as a weather station',
  'A refrigerator that has a built-in water filtration system',
  'A phone case that can also function as a wallet',
  'A building that incorporates green spaces to improve air quality and reduce heat island effect',
];
